### ISSUE TITLE
GNOME 44 Platform transition

### ISSUE THREAD

**Issue by fsobolev** [nlogozzo/NickvisionApplication#49]
GNOME 44 Platform with GTK 4.10 and Adw 1.3 [got released](https://release.gnome.org/44/developers/) and I think it would be nice to track all changes we might want to implement. I suggest to use only this issue instead of creating similar ones in other repos.

| | Application | Denaro | Tube Converter |
|---|---|---|---|
| Use 44 SDK in manifest | <li> [x] </li> | <li> [x] </li> | <li> [x] </li> |
| Gtk.FileChooserNative -> Gtk.FileDialog | <li> [x] </li> | <li> [x] </li> | <li> [x] </li> |
| Gtk.ColorButton -> Gtk.ColorDialogButton | | <li> [x] </li> | |
| Adw.ActionRow:icon-name -> [prefix] Gtk.Image | | <li> [x] </li> | |
| Adw.MessageDialog -> Adw.Window | | <li> [x] </li> | <li> [x] </li> |
| Show()/Hide() -> Present() or SetVisible() | <li> [x] </li> | <li> [x] </li> | <li> [x] </li> |

Feel free to edit this post if I missed something

**Comment by nlogozzo** [comment]
Im on mobile so can't really edit...buy Adw.MessageDialog --> Proper Adw.Window

**Comment by DaPigGuy** [comment]
I can do this for Tube Converter later today
